### PR TITLE
FIX babel-core including react-display-name & UPGRADE babel & other packages

### PR DESCRIPTION
**Pull request by ndelangen**
At first i just wanted to see if I could fix a small problem I had with a package `react-display-name` being loaded twice. See https://github.com/sapegin/react-styleguidist/commit/596c42d7cde87fb02fda48417d6f244bec7d4406

Then I thought what the hell, let's try upgrade to babel 6; as that's what I've wanted to do for a while.
Found a merge PR for react-styleguidist for doing just that, [here](https://github.com/sapegin/react-styleguidist/pull/81/commits) and pretty much followed that and fixed the stuff that came up.

### CODE REVIEW

**Comment by robhrt7** [comment]
Thanks for the PR, I'll try to check it today!

**Comment by robhrt7** [comment]
I started testing your changes with SourceJS react bundle example here in `dev` branch https://github.com/sourcejs/sourcejs-react-bundle-example and I got these errors, seems like JSX is not rendered by default:

```
ERROR in ./specs/placeholder/Placeholder.jsx
Module build failed: SyntaxError: /Users/robert-lg/Downloads/sourcejs-react-bundle-example/specs/placeholder/Placeholder.jsx: Unexpected token (28:3)
  26 |      let { width, height } = this.props;
  27 |      return (
> 28 |          <img className={s.root} src={this.getImageUrl()} width={width} height={height}/>
     |          ^
  29 |      );
  30 |  }
  31 | }
    at Parser.pp.raise (/Users/robert-lg/Downloads/sourcejs-react-styleguidist/node_modules/babel-core/node_modules/babylon/lib/parser/location.js:22:13)
    at Parser.pp.unexpected (/Users/robert-lg/Downloads/sourcejs-react-styleguidist/node_modules/babel-core/node_modules/babylon/lib/parser/util.js:89:8)
    at Parser.pp.parseExprAtom (/Users/robert-lg/Downloads/sourcejs-react-styleguidist/node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:517:12)
    at Parser.pp.parseExprSubscripts (/Users/robert-lg/Downloads/sourcejs-react-styleguidist/node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:272:19)
    at Parser.pp.parseMaybeUnary (/Users/robert-lg/Downloads/sourcejs-react-styleguidist/node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:252:19)
    at Parser.pp.parseExprOps (/Users/robert-lg/Downloads/sourcejs-react-styleguidist/node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:183:19)
    at Parser.pp.parseMaybeConditional (/Users/robert-lg/Downloads/sourcejs-react-styleguidist/node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:165:19)
    at Parser.pp.parseMaybeAssign (/Users/robert-lg/Downloads/sourcejs-react-styleguidist/node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:128:19)
    at Parser.pp.parseParenAndDistinguishExpression (/Users/robert-lg/Downloads/sourcejs-react-styleguidist/node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:590:26)
    at Parser.pp.parseExprAtom (/Users/robert-lg/Downloads/sourcejs-react-styleguidist/node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:476:19)
 @ ../sourcejs-react-styleguidist/loaders/styleguide.loader.js! 3:544-645

ERROR in ./specs/button/Button.jsx
Module build failed: SyntaxError: /Users/robert-lg/Downloads/sourcejs-react-bundle-example/specs/button/Button.jsx: Unexpected token (28:3)
  26 |
  27 |      return (
> 28 |          <button className={s.root} style={styles} onClick={this.onClick}>{this.props.children}</button>
     |          ^
  29 |      );
  30 |  }
  31 | }
    at Parser.pp.raise (/Users/robert-lg/Downloads/sourcejs-react-styleguidist/node_modules/babel-core/node_modules/babylon/lib/parser/location.js:22:13)
    at Parser.pp.unexpected (/Users/robert-lg/Downloads/sourcejs-react-styleguidist/node_modules/babel-core/node_modules/babylon/lib/parser/util.js:89:8)
    at Parser.pp.parseExprAtom (/Users/robert-lg/Downloads/sourcejs-react-styleguidist/node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:517:12)
    at Parser.pp.parseExprSubscripts (/Users/robert-lg/Downloads/sourcejs-react-styleguidist/node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:272:19)
    at Parser.pp.parseMaybeUnary (/Users/robert-lg/Downloads/sourcejs-react-styleguidist/node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:252:19)
    at Parser.pp.parseExprOps (/Users/robert-lg/Downloads/sourcejs-react-styleguidist/node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:183:19)
    at Parser.pp.parseMaybeConditional (/Users/robert-lg/Downloads/sourcejs-react-styleguidist/node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:165:19)
    at Parser.pp.parseMaybeAssign (/Users/robert-lg/Downloads/sourcejs-react-styleguidist/node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:128:19)
    at Parser.pp.parseParenAndDistinguishExpression (/Users/robert-lg/Downloads/sourcejs-react-styleguidist/node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:590:26)
    at Parser.pp.parseExprAtom (/Users/robert-lg/Downloads/sourcejs-react-styleguidist/node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:476:19)
 @ ../sourcejs-react-styleguidist/loaders/styleguide.loader.js! 3:165-256
```

Does changes to plugin require some changes to project as well?

**Comment by ndelangen** [comment]
> Does changes to plugin require some changes to project as well?

Unfortunately, yes: You need a new .babelrc in your project folder: 

```
{
    "presets": ["es2015", "react", "stage-0"]
}
```

**Comment by ndelangen** [comment]
I'm not sure if there's a way around that with the 'npm dependency install'-route.

But I think it's actually correct to have a .babelrc there.

**Comment by robhrt7** [comment]
That totally makes sense, since they decoupled the babel config from the project code. I will continue the testing.

**Comment by robhrt7** [comment]
I've made the bundle working in `dev` branch, but live reload is not working anymore. The changes are rebuilt, but not applied to the examples in the spec.

**Comment by ndelangen** [comment]
Does using this .babelrc make it work?

```
{
    "env": {
        "development": {
            "presets": [
                "react-hmre"
            ]
        }
    },
    "presets": ["es2015", "react", "stage-0"]
}
```

This is exactly what the plugin itself uses.

**Comment by robhrt7** [comment]
I've tested with new presets, now it's working fine, will merge it and release with breaking change version. Thanks again for your PR!

**Comment by ndelangen** [comment]
Super awesome! Happy to help!

**Pull request merged**
